# Copyright (C) 2018-2019 Lienol
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for adguardhome
LUCI_DEPENDS:=+luci-compat +wget +adguardhome
LUCI_PKGARCH:=all
PKG_VERSION:=1.8
PKG_RELEASE:=15

PKG_LICENSE:=MIT
PKG_MAINTAINER:=<https://github.com/rufengsuixing/luci-app-adguardhome>

include $(TOPDIR)/feeds/luci/luci.mk


# call BuildPackage - OpenWrt buildroot signature
