#
# Copyright (C) 2020 KGHX <openwrt.ikghx.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for ChinaDNS-NG.
LUCI_DEPENDS:=+chinadns-ng
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=1

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
