include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for RustDesk Server
LUCI_DEPENDS:=+luci-base +rpcd +rpcd-mod-ucode +rustdesk-server

PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
