#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Memcached.
LUCI_DEPENDS:=+memcached

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
