#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Footstrap >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Footstrap=/luci-static/footstrap
		set luci.main.mediaurlbase=/luci-static/footstrap
		commit luci
	EOF
fi

mkdir -p /etc/footstrap
if [ -d /www/luci-static/footstrap ]; then
	ln -sf /etc/footstrap/login-bg /www/luci-static/footstrap/bg
	ln -sf /etc/footstrap/pattern.svg /www/luci-static/footstrap/pattern.svg
	ln -sfn /etc/footstrap/fonts /www/luci-static/footstrap/fonts
fi

exit 0
