#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Footstrap >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Footstrap=/luci-static/footstrap
		set luci.main.mediaurlbase=/luci-static/footstrap
		commit luci
	EOF
fi

mkdir -p /etc/footstrap 2>/dev/null
[ -d /www/luci-static/footstrap ] && ln -sf /etc/footstrap/login-bg /www/luci-static/footstrap/bg 2>/dev/null
[ -d /www/luci-static/footstrap ] && ln -sf /etc/footstrap/pattern.svg /www/luci-static/footstrap/pattern.svg 2>/dev/null

if [ -d /www/luci-static/footstrap ]; then
	[ ! -e /www/luci-static/footstrap/fonts ] || [ -L /www/luci-static/footstrap/fonts ] ||
		rm -rf /www/luci-static/footstrap/fonts
	ln -sfn /etc/footstrap/fonts /www/luci-static/footstrap/fonts 2>/dev/null
fi

exit 0
