#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for oscam
LUCI_DEPENDS:=+oscam +kmod-usb-serial-ftdi +kmod-usb-serial-pl2303

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
