#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for hev-socks5-server.
LUCI_DEPENDS:=+hev-socks5-server

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
