#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for PHP8.
LUCI_DEPENDS:=+php8-mod-mysqli +php8-mod-mbstring +php8-mod-ldap \
+php8-mod-intl +php8-mod-imap +php8-mod-iconv +php8-mod-gmp +php8-mod-gettext \
+php8-mod-gd +php8-mod-ftp +php8-mod-fileinfo +php8-mod-filter +php8-mod-exif \
+php8-mod-dom +php8-mod-curl +php8-mod-ctype +php8-mod-calendar +php8-mod-bcmath \
+php8-fpm +php8-cli +php8-mod-phar +php8-mod-pdo-mysql +php8-mod-pcntl \
+php8-mod-openssl +php8-mod-opcache +php8-mod-sockets +php8-mod-soap \
+php8-mod-simplexml +php8-mod-shmop +php8-mod-session +php8-mod-zip +php8-mod-xmlwriter \
+php8-mod-xmlreader +php8-mod-xml +php8-mod-tokenizer +php8-mod-sysvshm +php8-mod-sysvsem \
+php8-mod-sysvmsg +php8-pecl-http +php8-pecl-dio \
+php8-pecl-mcrypt +php8-pecl-redis php8-pecl-imagick +php8-pecl-sodium

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
