#!/bin/sh

uci -q batch <<-EOF
	delete firewall.passwall
	set firewall.passwall=include
	set firewall.passwall.type='script'
	set firewall.passwall.path='/var/etc/passwall.include'

	set dhcp.@dnsmasq[0].localuse=1
	commit dhcp
EOF

if [ -x "/sbin/fw3" ]; then
	uci -q set firewall.passwall.reload='1'
else
	uci -q delete firewall.passwall.reload
	uci -q delete firewall.passwall.fw4_compatible
fi
uci commit firewall

[ ! -s "/etc/config/passwall" ] && cp -f /usr/share/passwall/0_default_config /etc/config/passwall

mkdir -p /etc/passwall/rules
for file in \
	direct_host \
	direct_ip \
	proxy_host \
	proxy_ip \
	block_host \
	block_ip \
	lanlist_ipv4 \
	lanlist_ipv6 \
	domains_excluded
do
	[ -f "/etc/passwall/rules/$file" ] || cp "/usr/share/passwall/rules/$file" "/etc/passwall/rules/$file"
done

exit 0
