#!/bin/sh

uci -q batch <<-EOF
	delete firewall.passwall_server
	set firewall.passwall_server=include
	set firewall.passwall_server.type='script'
	set firewall.passwall_server.path='/var/etc/passwall_server.include'
EOF

if [ -x "/sbin/fw3" ]; then
	uci -q set firewall.passwall_server.reload='1'
else
	uci -q delete firewall.passwall_server.reload
	uci -q delete firewall.passwall_server.fw4_compatible
fi
uci commit firewall

exit 0
