#!/bin/sh

uci -q batch <<-EOF
	delete firewall.passwall
	set firewall.passwall=include
	set firewall.passwall.type='script'
	set firewall.passwall.path='/var/etc/passwall.include'

	set dhcp.@dnsmasq[0].localuse=1
	commit dhcp
EOF

if [ -x "/sbin/fw3" ]; then
	uci -q set firewall.passwall.reload='1'
else
	uci -q delete firewall.passwall.reload
	uci -q delete firewall.passwall.fw4_compatible
fi
uci commit firewall

[ ! -s "/etc/config/passwall" ] && cp -f /usr/share/passwall/0_default_config /etc/config/passwall

exit 0
