#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for strongswan
LUCI_DEPENDS:=+strongswan-default +strongswan-swanctl

PKG_MAINTAINER:=KGHX
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
