#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=A Luci module that uses wrtbwmon to track bandwidth usage
LUCI_PKGARCH:=all
PKG_VERSION:=2.0.12
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

