#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for PHP7.
LUCI_DEPENDS:=+php7-mod-mysqli +php7-mod-mbstring +php7-mod-ldap +php7-mod-json \
+php7-mod-intl +php7-mod-imap +php7-mod-iconv +php7-mod-gmp +php7-mod-gettext \
+php7-mod-gd +php7-mod-ftp +php7-mod-fileinfo +php7-mod-filter +php7-mod-exif +php7-mod-dom \
+php7-mod-curl +php7-mod-ctype +php7-mod-calendar +php7-mod-bcmath \
+php7-fpm +php7-cli +php7-mod-phar +php7-mod-pdo-mysql +php7-mod-pcntl \
+php7-mod-openssl +php7-mod-opcache +php7-mod-sockets +php7-mod-soap \
+php7-mod-simplexml +php7-mod-shmop +php7-mod-session +php7-mod-zip +php7-mod-xmlwriter \
+php7-mod-xmlreader +php7-mod-xml +php7-mod-tokenizer +php7-mod-sysvshm +php7-mod-sysvsem \
+php7-mod-sysvmsg +php7-pecl-http +php7-pecl-libevent +php7-pecl-dio \
+php7-pecl-mcrypt +php7-pecl-redis +php7-pecl-imagick +php7-pecl-sodium

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
