#!/bin/sh

uci -q batch <<-EOF >"/dev/null"
	delete firewall.unblockneteasemusic
	set firewall.unblockneteasemusic=include
	set firewall.unblockneteasemusic.type=script
	set firewall.unblockneteasemusic.path=/var/run/unblockneteasemusic/fw3.include
	set firewall.unblockneteasemusic.reload=1
	commit firewall
EOF

exit 0
