#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.unblockneteasemusic
	set firewall.unblockneteasemusic=include
	set firewall.unblockneteasemusic.type=script
	set firewall.unblockneteasemusic.path=/var/etc/unblockneteasemusic.include
	set firewall.unblockneteasemusic.reload=1
	commit firewall
EOF

/etc/init.d/rpcd reload
exit 0
