#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Mariadb.
LUCI_DEPENDS:=+mariadb-server-extra +mariadb-client-extra

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
