#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for DNSCrypt-Proxy2.
LUCI_DEPENDS:=+dnscrypt-proxy2

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
