#!/bin/sh

mkdir -p /etc/mosdns/rule
touch /etc/mosdns/rule/whitelist.txt
touch /etc/mosdns/rule/blocklist.txt
touch /etc/mosdns/rule/hosts.txt
touch /etc/mosdns/rule/local-ptr.txt
touch /etc/mosdns/rule/redirect.txt

exit 0
