# Copyright (C) 2016 Openwrt.org
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for arptables
LUCI_DEPENDS:=+arptables
LUCI_PKGARCH:=all
PKG_LICENSE:=GPLv2

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
