#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for cupsd
LUCI_DEPENDS:=+kmod-usb-printer +kmod-usb-storage \
+cups-bjnp +cups-bsd +cups-client +cups-filters +cups-ppdc

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
