#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.weburl
	set firewall.weburl=include
	set firewall.weburl.type=script
	set firewall.weburl.path=/etc/weburl.include
	set firewall.weburl.reload=1
	commit firewall
EOF

exit 0
