#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2015 OpenWrt.org

START=90
USE_PROCD=1

start_instance() {
	config_load "vlmcsd"

	local cfg="$1"
	local enabled autoactivate

	config_get_bool enabled "$cfg" 'enabled' 0
	[ $enabled -gt 0 ] || return 1

	config_get autoactivate "$cfg" autoactivate 1

	HOSTNAME=$(uci get system.@system[0].hostname)
	host_name=$(awk -F ',' '/^[ \t]*srv-host=_vlmcs\._tcp/{print $2}' /etc/dnsmasq.conf)

	echo $HOSTNAME
	echo $host_name

	if [ "$HOSTNAME" != "$host_name" ];then
		sed -i '/^[ \t]*srv-host=_vlmcs\._tcp/d' /etc/dnsmasq.conf
		sed -i '$a\srv-host=_vlmcs\._tcp,'"$HOSTNAME"','"1688"',0,100' /etc/dnsmasq.conf
		/etc/init.d/dnsmasq restart >/dev/null 2>&1
	fi

	procd_open_instance
	procd_set_param command /usr/bin/vlmcsd -D -i /etc/vlmcsd.ini
	procd_append_param command -l /var/log/vlmcsd.log

	procd_set_param respawn

	procd_set_param file /etc/vlmcsd.ini
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

start_service() {
	config_load vlmcsd
	config_foreach start_instance vlmcsd
}

service_triggers() {
	procd_add_reload_trigger "vlmcsd"
}
