# This is free software, licensed under the Apache License, Version 2.0

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Webd.
LUCI_DEPENDS:=+webd

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=KGHX <openwrt.ikghx.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
