# This is free software, licensed under the Apache License, Version 2.0

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for N2N VPN.
LUCI_DEPENDS:=+luci-compat +n2n-edge +n2n-supernode

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=KGHX <openwrt.ikghx.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
