# Copyright (C) 2021 Openwrt.org
#
# This is a free software, use it under Apache Licene 2.0 & GNU General Public License v3.0.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for HAProxy
LUCI_DEPENDS:=+haproxy
LUCI_PKGARCH:=all
PKG_MAINTAINER:=KGHX
PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
