#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.ipsecvpn
	set firewall.ipsecvpn=include
	set firewall.ipsecvpn.type=script
	set firewall.ipsecvpn.path=/var/etc/ipsecvpn.include
	set firewall.ipsecvpn.reload=1
EOF

exit 0
