#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.zerotier
	set firewall.zerotier=include
	set firewall.zerotier.type=script
	set firewall.zerotier.path=/etc/zerotier.start
	set firewall.zerotier.reload=1
	commit firewall
EOF

exit 0
