#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.v2ray
	set firewall.v2ray=include
	set firewall.v2ray.type=script
	set firewall.v2ray.path=/etc/firewall.v2ray
	set firewall.v2ray.family=any
	set firewall.v2ray.reload=1
	commit firewall
EOF

/etc/init.d/rpcd reload

exit 0
