#!/bin/sh /etc/rc.common
# Copyright (c) 2011-2015 OpenWrt.org

START=60
SH="/etc/mwan3helper/genipset.sh"
del="ipset -! destroy"

start() {
	enabled=$(uci get mwan3helper.config.enabled)
	[ $enabled -eq 0 ] && exit 0
	$SH allcn '/etc/mwan3helper/all_cn.txt'
	$SH ct '/etc/mwan3helper/chinatelecom.txt'
	$SH cu '/etc/mwan3helper/unicom_cnc.txt'
	$SH cmcc '/etc/mwan3helper/cmcc.txt'
	$SH crtc '/etc/mwan3helper/crtc.txt'
	$SH cernet '/etc/mwan3helper/cernet.txt'
	$SH gwbn '/etc/mwan3helper/gwbn.txt'
	$SH othernet '/etc/mwan3helper/othernet.txt'
	$SH hk '/etc/mwan3helper/hk.txt'
	$SH mo '/etc/mwan3helper/mo.txt'
	$SH tw '/etc/mwan3helper/tw.txt'
	$SH allcn6 '/etc/mwan3helper/all_cn_ipv6.txt'
	$SH ct6 '/etc/mwan3helper/chinatelecom_ipv6.txt'
	$SH cu6 '/etc/mwan3helper/unicom_cnc_ipv6.txt'
	$SH cmcc6 '/etc/mwan3helper/cmcc_ipv6.txt'
	$SH crtc6 '/etc/mwan3helper/crtc_ipv6.txt'
	$SH cernet6 '/etc/mwan3helper/cernet_ipv6.txt'
	$SH gwbn6 '/etc/mwan3helper/gwbn_ipv6.txt'
	$SH othernet6 '/etc/mwan3helper/othernet_ipv6.txt'
	$SH hk6 '/etc/mwan3helper/hk_ipv6.txt'
	$SH mo6 '/etc/mwan3helper/mo_ipv6.txt'
	$SH tw6 '/etc/mwan3helper/tw_ipv6.txt'
}

stop() {
	$del allcn
	$del ct
	$del cu
	$del cmcc
	$del crtc
	$del cernet
	$del gwbn
	$del othernet
	$del hk
	$del mo
	$del tw
	$del allcn6
	$del ct6
	$del cu6
	$del cmcc6
	$del crtc6
	$del cernet6
	$del gwbn6
	$del othernet6
	$del hk6
	$del mo6
	$del tw6
}

